version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mini-store-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo-data:/data/db
    command: ["--wiredTigerCacheSizeGB", "1"]
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand({ ping: 1 }).ok' | grep 1"]
      interval: 10s
      timeout: 5s
      retries: 5

# (Opcional) UI web para explorar la BD
#  mongo-express:
#    image: mongo-express:1.0.2-20
#    container_name: mini-store-mongo-express
#    depends_on:
#      - mongo
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_URL: "mongodb://mongo:27017"
